#id:MATERIAL_NAME is to represent an items material id.
#name:string is to represent part of the display name of an item
#NoEntry prevents the item from being used in an Anvil
#NoRename prevents the rename of an item.

NoEntry: id|SAND,name|Proximity Sensor
NoRename: id|RED_SAND
NoRenameAll: false
NoEntryAll: false