name: AnvilRestrict
version: ${project.version}
authors: [ Ugleh, poma123, Baterka ]
main: me.poma123.anvilrestrict.AnvilRestrict
api-version: 1.16
commands:
    anvilrestrict:
        usage: /<command>
        aliases: [ar, anvilr]
permissions:
    anvilrestrict.admin:
        default: op
