name: AnvilRestrict
version: ${project.version}
authors: [ Ugleh, poma123, Baterka ]
main: com.thegeekedgamer.anvilrestrict.AnvilRestrict
api-version: 1.17
commands:
    anvilrestrict:
        usage: /<command>
        aliases: [ar, anvilr]
permissions:
    anvilrestrict.admin:
        default: op
