# Prevents all items from being renamed in an Anvil
NoRenameAll: false

# Prevents all items from being used in an Anvil
NoEntryAll: false

# Prevents defined items from being used in an Anvil
# Example - id:<MATERIAL_NAME>,name|<ITEM_NAME>
NoEntry: id|SAND,name|Proximity Sensor

# Prevents defined items from being renamed in an Anvil
# Example - id:<MATERIAL_NAME>,name|<ITEM_NAME>
NoRename: id|RED_SAND